// <auto-generated />
namespace KomodoDevTeams.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class contractmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contractmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201810222004275_contract-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
